### ISSUE TITLE
DOD: DOI estimate field as mandatory field

### ISSUE THREAD

**Issue by kjgarza** [datacite/tasks#90]
# DOD: DOI estimate field as mandatory field

### Development Checklist
- [x] Passed through peer review see Pull Request Guidelines
- [x] Unit, integration, and system tests that all pass on the CI.
- [x] Regressions and bugs are covered (where relevant) with tests that reduce the risk of the issue happening again.
- [x] Reviewed by relevant reviewers and all comments are addressed.
- [x] Confirmed to be working in the stage environment with no new Sentry errors.
- [x] Confirmed that user stories are met:

- [x] Feature 1: DOI estimate field
  - [x] Scenario 1.1:  DOI estimated field for year one in the form
  - [x] Scenario 1.2:  Create a new Consortium Organisation
  - [x] Scenario 1.3:  Update Consortium Organisation
- [x] Feature 2: Other Services effects
  - [x] Scenario 2.1: Salesforce Consortium update

### Product Engineering Checklist
- [x] Feature 1: DOI estimate field
  - [x] Scenario 1.1:  DOI estimated field for year one in the form
  - [x] Scenario 1.2:  Create a new Consortium Organisation
  - [x] Scenario 1.3:  Update Consortium Organisation
- [x] Feature 2: Other Services effects
  - [x] Scenario 2.1: Salesforce Consortium update
- [x] Feature Flag has been removed. (where relevant)

### Engagement Checklist
- [x] Documentation has been updated
~~- [ ] Blogpost/newsletter has been written~~ (not needed according to RADs call 10/03/22 )

**Comment by kjgarza** [comment]
@svogt0511 I think the help text needs to be updated https://docs.google.com/document/d/14IAGf1hQzKeY3BPsixUv78IYuQiyIAU5_nY78IThf8k/edit#bookmark=id.oe8yjzgaglv7

**Comment by svogt0511** [comment]
Pushing the fixed help text wording to the staging environment. Should be there soon.

--- original message ---
On March 9, 2022, 11:40 AM EST ***@***.*** wrote:



@svogt0511 I think the help text needs to be updated https://docs.google.com/document/d/14IAGf1hQzKeY3BPsixUv78IYuQiyIAU5_nY78IThf8k/edit#bookmark=id.oe8yjzgaglv7

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you were mentioned.Message ID: ***@***.***>
--- end of original message ---

**Comment by kjgarza** [comment]
@svogt0511 I think the Test database also needs to be migrated

**Comment by svogt0511** [comment]
Just checked, the test database has been migrated. What indicates that it has not been migrated?

--- original message ---
On March 11, 2022, 7:45 AM EST ***@***.*** wrote:



@svogt0511 I think the Test database also needs to be migrated

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you were mentioned.Message ID: ***@***.***>
--- end of original message ---

**Comment by kjgarza** [comment]
https://app.frontapp.com/open/msg_hetjj4l
